# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
lidar_joint_velocity_controller:
  type: effort_controllers/JointVelocityController 
  joint: lidar_joint 
  pid: {p: 200, i: 15, d: 5}
  
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1
  pid: {p: 200, i: 15, d: 5}  #100, 80, 50

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2
  pid: {p: 200, i: 10, d: 5}


joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint3
  pid: {p: 200, i: 15, d: 5}


joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint4
  pid: {p: 200, i: 15, d: 5}


joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint5
  pid: {p: 200, i: 15, d: 5}


joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint6
  pid: {p: 200, i: 15, d: 100}



